#pragma once

#include <unordered_set>
#include <mutex>
#include <string>

#include "FileQueue.hpp"

//! A global context. Used to pass around a ball of variables shared by lots of the code.
struct Context {
	bool verbose; //!< True to print additional information to stdout
	std::unordered_set<std::string> generatedFiles; //!< LaTeX files generated by SemTeX
	std::mutex generatedFilesMutex; //!< A mutex for generatedFiles
	FileQueue queue; //!< Queue of SemTeX files to be processed

	//! Constructor (just hands callback to queue)
	Context(FileQueue::SeveralCallback cb) : queue(cb) { }
};
